name: 'alpaca_trading_bot'
version: '1.0.0'
config-version: 2

# Questo nome DEVE corrispondere a quello iniziale che metti nel profiles.yml
profile: 'alpaca_profile'

# Cartelle dove dbt cercherà i tuoi modelli SQL e i test
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  alpaca_trading_bot:
    # Configurazione di default per i tuoi modelli (es. crea viste)
    materialized: view